services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - kademlia-network-broadcast
    cap_add:
      - NET_BROADCAST
    ports:
      - "8081:54321"
      - "8091:19009/udp"
    volumes:
      - .:/app

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - kademlia-network-broadcast
    cap_add:
      - NET_BROADCAST
    ports:
      - "8082:54321"
      - "8092:19009/udp"
    volumes:
      - .:/app

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - kademlia-network-broadcast
    cap_add:
      - NET_BROADCAST
    ports:
      - "8083:54321"
      - "8093:19009/udp"
    volumes:
      - .:/app
  node4:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - kademlia-network-broadcast
    cap_add:
      - NET_BROADCAST
    ports:
      - "8084:54321"
      - "8094:19009/udp"
    restart: no
    volumes:
      - .:/app
networks:
  kademlia-network-broadcast:
    driver: bridge
